### ISSUE TITLE
Data Not Being Parsed 

### ISSUE THREAD

**Issue by prabh1601** [DrSchwad/FastOlympicCodingHook#2]
Hey hi ... I have been using this tool at windows machine for quite a while now and it is the exact  thing I was looking for but I have ran of a problem now .
I have switched to ubuntu and using the same things as I did for my previous machine .. This thing is not parsing the data in my cppFastOlympicCoding plugin .. 
I would be available to give any further information u would require for the same and would really request u to look into my query becz this is one thing without which I cant really code my way into cp ... 
Regards

**Comment by prabh1601** [comment]
One unusual thing that I observed that the test file is still being saved with __tests suffix as it used to do in windows and I suppose it is supposed to be saved :tests suffix .. So this might be thing to notice

**Comment by DrSchwad** [comment]
Thank you for the observation, that helps a lot. You're right about the issue, the file is being saved with wrong suffix. Can you kindly run the following command in your terminal and let me know the output -
`python3 -c "import platform; print(platform.system());"`

**Comment by prabh1601** [comment]
It shows Linux as the output ...

**Comment by prabh1601** [comment]
Ok What I did is tweaked the script of this extension a bit and changed the default suffix for nfilename to be "__tests" across all the platforms instead of explicitly changing it to "__tests" for only windows and it works now .. I guess __tests is better compactable suffix since I also have gone through this problem across various comments on codeforces blog also . So you can consider changing the if condition in the script you have written for the windows platform and just write nfilename = .... + "__tests". This would work for all the platforms I guess

**Comment by DrSchwad** [comment]
Great to hear that you got it resolved! But I had really thought that only Windows required the "__" suffix, since as far as I remember I read in an StackOverflow answer that Windows faces issues with ":" in filenames.

Thank you for the suggestion, I'll try to check if all three OS support "__" suffix. But can you kindly recall if you tweaked the FastOlympicCoding settings and added the line `"tests_file_suffix": "__tests"` there, as you did previously with Windows? If so, then that could possibly have been the cause of your issue.

If you did tweak the settings then that answers everything, otherwise a lot of other users might be facing this same issue. So please let me know about it.

**Comment by prabh1601** [comment]
Actually ... When I first Installed the FastOlympicCoding plugin it was not running as is was supposed to be with what I mean is that It was not stopping after I give the whole input ... I had to explicitly stop the test ... Out of frustration what I did was copied the exact same process of windows by adding the suffix of __tests both in main plugin and this extension ... And it worked .. luck of chance rather .. but after that I tried the same with :tests suffix the same thing and yeah it worked ... So that is where I got the idea that instead of having different suffix across the different platform ... what can be done is forcefully having same suffix across both the extension (fastOlympicCoding and this hook) which would make the thing just ready to go as installed

**Comment by prabh1601** [comment]
But I dont think that adding a single line of code in the windows setting by the user would much of a difference for a one time thing but surely this can make life simple rather... Anyways Thanks for the extension man this has made the task so simple and has been a much help than you can expect !

**Comment by DrSchwad** [comment]
Glad to help :) And thank you very much for sharing your observations here and informing me all the details. I really appreciate that. I'll try to find a consistent way across all the three major OSs.
